job:
  image: hmctspublic.azurecr.io/nfdiv/case-api:latest
  aadIdentityName: nfdiv
  keyVaults:
    nfdiv:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: APP_INSIGHTS_KEY
        - name: uk-gov-notify-api-key
          alias: UK_GOV_NOTIFY_API_KEY
        - name: s2s-case-api-secret
          alias: S2S_SECRET
        - name: idam-secret
          alias: IDAM_CLIENT_SECRET
        - name: idam-systemupdate-username
          alias: IDAM_SYSTEM_UPDATE_USERNAME
        - name: idam-systemupdate-password
          alias: IDAM_SYSTEM_UPDATE_PASSWORD
  environment:
    NOTIFY_TEMPLATE_SIGN_IN_DIVORCE_URL: https://nfdiv-apply-for-divorce.aat.platform.hmcts.net/
    NOTIFY_TEMPLATE_SIGN_IN_DISSOLUTION_URL: https://nfdiv-end-civil-partnership.aat.platform.hmcts.net/
    NOTIFY_TEMPLATE_APPLICANT2_SIGN_IN_DIVORCE_URL: https://nfdiv-apply-for-divorce.aat.platform.hmcts.net/applicant2
    NOTIFY_TEMPLATE_APPLICANT2_SIGN_IN_DISSOLUTION_URL: https://nfdiv-end-civil-partnership.aat.platform.hmcts.net/applicant2
    S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    FEE_API_URL: http://fees-register-api-aat.service.core-compute-aat.internal
    IDAM_API_REDIRECT_URL: https://div-pfe-aat.service.core-compute-aat.internal/authenticated
    IDAM_API_BASEURL: "https://idam-api.aat.platform.hmcts.net"
    CASE_DATA_STORE_BASEURL: "http://ccd-data-store-api-aat.service.core-compute-aat.internal"
    DOC_ASSEMBLY_URL: http://dg-docassembly-aat.service.core-compute-aat.internal
    DOCUMENT_MANAGEMENT_URL: http://dm-store-aat.service.core-compute-aat.internal
    PRD_API_BASEURL : "http://rd-professional-api-aat.service.core-compute-aat.internal"
    SEND_LETTER_SERVICE_BASEURL: "http://rpe-send-letter-service-aat.service.core-compute-aat.internal"
    SERVICE_AUTH_PROVIDER_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    SERVICE_AUTH_MICROSERVICE: nfdiv_case_api
  args:
    - run
    - SystemRemindApplicant2Task
  schedule: "0 0/10 * * *"
  concurrencyPolicy: Forbid
global:
  jobKind: CronJob
  enableKeyVaults: true
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
